name: Unzip
on: workflow_dispatch
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip opay folder
        run: |
          unzip -o "opay (2).zip" -d temp
          rm -rf app/src
          mv temp/opay*/app/src app/src || mv temp/app/src app/src || cp -r temp/opay*/app/src app/ || true
          rm -rf temp "opay (2).zip"
          ls -R app
      - uses: stefanzweifel/git-auto-commit-action@v5
